### 상품 좋아요 토글
POST http://localhost:8080/api/products/1/like
Authorization: {{Authorization}}
Content-Type: application/json

{
  "contentType": "PRODUCT",
  "contentId": 1
}


### 댓글 좋아요 토글
POST http://localhost:8080/api/comments/1/like
Authorization: {{Authorization}}
Content-Type: application/json

{
  "contentType": "COMMENT",
  "contentId": 1
}